config/routes.rb
Rails.application.routes.draw do

  # 顧客用画面（トップページ）
  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"

  # 顧客用画面（ログイン、新規登録）
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 顧客用画面（Itemsコントローラ）
  get "/items" => "public/items#index"
  get "/items/:id" => "public/items#show", as: "show_items"

  # 顧客用画面（Customersコントローラ)
  get "/customers/my_page" => "public/customers#show"
  get "/customers/information/edit" => "public/customers#edit"
  patch "/end_users/information" => "public/customers#update"
  get "/customers/unsubscribe" => "public/customers#unsubscribe"
  patch "/customers/unsubscribe" => "public/customers#update_unsubscribe", as: "update_unsubscribe"

  # 顧客用画面（Cart_itemsコントローラ）
  get "/cart_items" => "public/cart_items#index"
  patch "/cart_items/:id" => "public/cart_items#update", as: "update_cart_items"
  delete "/cart_items/destroy_all" => "public/cart_items#destroy_all", as: "destroy_all_cart_items"
  delete "/cart_items/:id" => "public/cart_items#destroy", as: "destory_cart_items"
  post "/cart_items" => "public/cart_items#create", as: "add_cart_items"

  # 顧客用画面（Ordersスコントローラ）
  get "/orders/new" => "public/orders#new"
  post "/orders/confirm" => "public/orders#confirm"
  get "/orders/complete" => "public/orders#complete"
  post "/orders" => "public/orders#create"
  get "/orders" => "public/orders#index", as: "orders_index"
  get "/orders/:id" => "public/orders#show", as: "show_orders"

  # 顧客用画面（Addressesコントローラ）
  get "/addresses" => "public/addresses#index"
  get "/addresses/:id/edit" => "public/addresses#edit", as: "edit_addresses"
  post "/addresses" => "public/addresses#create", as: "add_addresses"
  patch "/addresses/:id" => "public/addresses#update", as: "update_addresses"
  delete "/addresses/:id" => "public/addresses#destroy", as: "destroy_addresses"


  # 管理者用画面（トップページ）
  get "/admin" => "admin/homes#top"

  # 管理者用画面（ログイン）
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者用画面（Itemsコントローラ）
  get "/admin/items" => "admin/items#index"
  get "/admin/items/new" => "admin/items#new"
  post "/admin/items" => "admin/items#create", as: "admin_add_items"
  get "/admin/items/:id" => "admin/items#show", as: "admin_show_items"
  get "/admin/items/:id/edit" => "admin/items#edit", as: "admin_edit_items"
  patch "/admin/items/:id" => "admin/items#update", as: "admin_update_items"

  # 管理者用画面（Genresコントローラ）
  get "/admin/genres" => "admin/genres#index"
  post "/admin/genres" => "admin/genres#create", as: "admin_create_genres"
  get "/admin/genres/:id/edit" => "admin/genres#edit", as: "admin_edit_genres"
  patch "/admin/genres/:id" => "admin/genres#update", as: "admin_update_genres"

  # 管理者用画面（Customersコントローラ）
  get "/admin/customers" => "admin/customers#index"
  get "/admin/customers/:id" => "admin/customers#show", as: "admin_show_customers"
  get "/admin/customers/:id/edit" => "admin/customers#edit", as: "admin_edit_customers"
  patch "/admin/customers/:id" => "admin/customers#update", as: "admin_update_customers"

  # 管理者用画面（Ordersコントローラ）
  get "/admin/orders/:id" => "admin/orders#show", as: "admin_show_orders"
  patch "/admin/orders/:id" => "admin/orders#update", as: "admin_update_orders"
  

  # 管理者用画面（Order_detailsコントローラ）
  patch "/admin/order_details/:id" => "admin/order_details#update", as: "admin_update_order_details"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates:last_name, presence:true
  validates:first_name, presence:true
  validates:last_name_kana, presence:true
  validates:first_name_kana, presence:true
  validates:email, presence:true
  validates:encrypted_password, presence:true
  validates:postal_code, presence:true
  validates:address, presence:true
  validates:telephone_number, presence:true
  validates:is_deleted,inclusion:[true, false]

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_show_customers_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<p></p>

<div class ="container">
    <div class ="col-md-5">
        <h3 class ="bg-light" ><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>
    </div>
    <div class ="row">
        <div class ="col-md-8">
            <%= form_with model: @customer, url:admin_update_customers_path(@customer) do |f| %>
            <table class ="table table-borderless">
                <tr>
                    <td>会員ID</td>
                    <td><%= @customer.id %></td>
                </tr>
                <tr>
                    <td>氏名</td>
                    <td><%= f.text_field :last_name, size:"20", class:"mr-5" %><%= f.text_field :first_name, size:"20" %></td>
                </tr>
                <tr>
                    <td>フリガナ</td>
                    <td><%= f.text_field :last_name_kana, size:"20", class:"mr-5" %><%= f.text_field :first_name_kana, size:"20" %></td>
                </tr>
                <tr>
                    <td>郵便番号</td>
                    <td><%= f.text_field :postal_code, size:"20" %></td>
                </tr>
                <tr>
                    <td>住所</td>
                    <td><%= f.text_field :address, size:"62" %></td>
                </tr>
                <tr>
                    <td>電話番号</td>
                    <td><%= f.text_field :telephone_number, size:"20" %></td>
                </tr>
                <tr>
                    <td>メールアドレス</td>
                    <td><%= f.text_field :email, size:"20" %></td>
                </tr>
                <tr>
                    <td>会員ステータス</td>
                    <td>
                        <%= f.radio_button :is_deleted, :false %>
                        <%= f.label :is_deleted, "有効", value: false, class:"pr-3 border-bottom" %>
                        <%= f.radio_button :is_deleted, :true %>
                        <%= f.label :is_deleted, "退会", value: true, class:"border-bottom" %>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><%= f.submit '変更を保存', class:"btn btn-success btn-lg" %></td>
                </tr>
                
            </table>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/customers/index.html.erb
<p></p>

<div class ="container">
  <div class ="col-md-2">
    <h3 class ="bg-light">会員一覧</h3>
  </div>
  <div class ="row">
    <div class ="col-md-8 mx-auto">
      <table class ="table">
      <thead class ="bg-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <% @customers.each do |customer| %>
      <tbody>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_show_customers_path(customer) do %>
              <span class ="text-dark border-bottom border-dark"><%= customer.last_name %><%= customer.first_name %></span>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == false %>
              <span class ="text-success font-weight-bold">有効</span>
              <% else %>
              <span class ="text-secondary font-weight-bold">退会</span>
            <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
      </table>
      
    </div>
  </div>
  <div class=" col-md-12 d-flex justify-content-center"><%= paginate @customers %></div>
</div>

app/views/admin/customers/show.html.erb
<p></p>


<div class ="container">
  <div class ="col-md-6">
    <h3 class ="bg-light">
      <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
    </h3>
  </div>
  
  <div class ="row">
    <div class ="">
      <table class ="table table-borderless">
        <tbody>
          
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %><%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_deleted == false %>
              <span class ="text-success font-weight-bold">有効</span>
              <% else %>
              <span class ="text-secondary font-weight-bold">退会</span>
              <% end %>
              </td>
          </tr>
          <tr>
            <td></td>
            <td>
            <%= link_to '編集する', admin_edit_customers_path, class:"btn btn-success mr-5" %>
            
            <!--顧客ごとの注文履歴一覧にとばす？今は全体の一覧-->
            
            <%= link_to '注文履歴一覧を見る',admin_path, class:"btn btn-primary" %>
            </td>
          </tr>
          
        </tbody>
      </table>
    </div>
  </div>
</div>