config/routes.rb
Rails.application.routes.draw do

  # 顧客用画面（トップページ）
  root to: "public/homes#top"
  get "/about" => "public/homes#about", as: "about"

  # 顧客用画面（ログイン、新規登録）
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 顧客用画面（Itemsコントローラ）
  get "/items" => "public/items#index"
  get "/items/:id" => "public/items#show", as: "show_items"

  # 顧客用画面（Customersコントローラ)
  get "/customers/my_page" => "public/customers#show"
  get "/customers/information/edit" => "public/customers#edit"
  patch "/end_users/information" => "public/customers#update"
  get "/customers/unsubscribe" => "public/customers#unsubscribe"
  patch "/customers/unsubscribe" => "public/customers#update_unsubscribe", as: "update_unsubscribe"

  # 顧客用画面（Cart_itemsコントローラ）
  get "/cart_items" => "public/cart_items#index"
  patch "/cart_items/:id" => "public/cart_items#update", as: "update_cart_items"
  delete "/cart_items/destroy_all" => "public/cart_items#destroy_all", as: "destroy_all_cart_items"
  delete "/cart_items/:id" => "public/cart_items#destroy", as: "destory_cart_items"
  post "/cart_items" => "public/cart_items#create", as: "add_cart_items"

  # 顧客用画面（Ordersスコントローラ）
  get "/orders/new" => "public/orders#new"
  post "/orders/confirm" => "public/orders#confirm"
  get "/orders/complete" => "public/orders#complete"
  post "/orders" => "public/orders#create"
  get "/orders" => "public/orders#index", as: "orders_index"
  get "/orders/:id" => "public/orders#show", as: "show_orders"

  # 顧客用画面（Addressesコントローラ）
  get "/addresses" => "public/addresses#index"
  get "/addresses/:id/edit" => "public/addresses#edit", as: "edit_addresses"
  post "/addresses" => "public/addresses#create", as: "add_addresses"
  patch "/addresses/:id" => "public/addresses#update", as: "update_addresses"
  delete "/addresses/:id" => "public/addresses#destroy", as: "destroy_addresses"


  # 管理者用画面（トップページ）
  get "/admin" => "admin/homes#top"

  # 管理者用画面（ログイン）
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者用画面（Itemsコントローラ）
  get "/admin/items" => "admin/items#index"
  get "/admin/items/new" => "admin/items#new"
  post "/admin/items" => "admin/items#create", as: "admin_add_items"
  get "/admin/items/:id" => "admin/items#show", as: "admin_show_items"
  get "/admin/items/:id/edit" => "admin/items#edit", as: "admin_edit_items"
  patch "/admin/items/:id" => "admin/items#update", as: "admin_update_items"

  # 管理者用画面（Genresコントローラ）
  get "/admin/genres" => "admin/genres#index"
  post "/admin/genres" => "admin/genres#create", as: "admin_create_genres"
  get "/admin/genres/:id/edit" => "admin/genres#edit", as: "admin_edit_genres"
  patch "/admin/genres/:id" => "admin/genres#update", as: "admin_update_genres"

  # 管理者用画面（Customersコントローラ）
  get "/admin/customers" => "admin/customers#index"
  get "/admin/customers/:id" => "admin/customers#show", as: "admin_show_customers"
  get "/admin/customers/:id/edit" => "admin/customers#edit", as: "admin_edit_customers"
  patch "/admin/customers/:id" => "admin/customers#update", as: "admin_update_customers"

  # 管理者用画面（Ordersコントローラ）
  get "/admin/orders/:id" => "admin/orders#show", as: "admin_show_orders"
  patch "/admin/orders/:id" => "admin/orders#update", as: "admin_update_orders"
  

  # 管理者用画面（Order_detailsコントローラ）
  patch "/admin/order_details/:id" => "admin/order_details#update", as: "admin_update_order_details"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_for_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    # @customer = @order.customer
    # @order_details = OrderDetail.all
    @total = 0
    @total_amount = 0
    @name = @order.customer.last_name + @order.customer.first_name
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    
    @order_details.each do |order_detail|
      if @order.order_status == "payment_confirmation"
        order_detail.update(production_status:"waiting_for_production")
      end
    end
    redirect_to admin_show_orders_path
  end

  def index
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.page(params[:page])
    # @cart_items = @customer.cart_items
    @total_amount = 0
    @order_details = OrderDetail.all
  end

private

  def order_params
  params.require(:order).permit(:customer_id, :postal_code, :address, :name, :payment_method, :postage, :billing_amount, :order_status)
  end

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end

  def order_detail_params
    params.require(:order_detail).permit(:item_id, :order_id, :amount, :tax_included_price, :production_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<p></p>

<div class="container">
  <div class="col-md-3">
    <h3 class="bg-light">注文履歴詳細</h3>
  </div>

  <div class="row">
    <div class="mt-3">
    <div class="col-md-12">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to @name, admin_path(by_customer_orders: @name), method: :get, class:"text-body" %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <span><%= @order.postal_code %> <%= @order.address %></span><br />
            <span><%= @order.name %></span>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_show_orders_path(@order) do |f| %>
            <%= f.select :order_status, Order.order_statuses_i18n.keys.map{|k| [I18n.t("enums.order.order_status.#{k}"), k]} %><%= f.submit'更新', class:"btn btn-success btn-sm ml-4" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    </div>
    </div>
  </div>

  <div class="row">
  <div class="col-md-8 mt-4">
    <table class ="table table-borderless border-top border-bottom">
        <thead class ="bg-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.tax_included_price %></td>
            <td><%= order_detail.amount %></td>
            <% @total_amount += order_detail.amount %>
            <td><%= order_detail.tax_included_price * order_detail.amount %></td>
            <% @total += order_detail.tax_included_price * order_detail.amount %>
            <td>
            <%= form_with model: order_detail, url: admin_update_order_details_path(order_detail) do |f| %>
            <%= f.select :production_status, OrderDetail.production_statuses_i18n.keys.map{|k| [I18n.t("enums.order_detail.production_status.#{k}"), k]} %><%= f.submit'更新', class:"btn btn-success btn-sm ml-4" %>
            <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
    </table>
  </div>

    <div class ="col-md-3 mt-5">
    <table class ="table table-borderless">
      <tbody>
        <tr>
          <th>商品合計</th>
          <td><%= @total_amount %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <th><%= @order.postage + @total %></th>
        </tr>
      </tbody>
    </table>
  </div>
  </div>


</div>